// packages/gent-gui/src/App.tsx
import { createAjv, type JsonSchema } from "@jsonforms/core";
import { JsonForms } from "@jsonforms/react";
import { vanillaCells, vanillaRenderers } from "@jsonforms/vanilla-renderers";
import type { ErrorObject } from "ajv";
import { useMemo, useState } from "react";
import "./App.css";
import { generationProfileSchema } from "@gent-js/gent/generated/schema/generatedGenerationProfileSchema";
import { initialGenerationProfile } from "./schema/initialGenerationProfile";

function App() {
  const [profile, setProfile] = useState<Record<string, unknown>>(
    initialGenerationProfile,
  );
  const [errors, setErrors] = useState<ErrorObject[]>([]);

  const ajv = useMemo(() => {
    const instance = createAjv({ allErrors: true, strict: false });
    return instance;
  }, []);

  const generatedProfile = useMemo(
    () => JSON.stringify(profile, null, 2),
    [profile],
  );

  return (
    <main className="app">
      <header>
        <h1>GenT Profile Builder</h1>
        <p className="lead">
          Fill in the form generated from the GenT generation profile schema.
        </p>
      </header>

      <section className="panel">
        <h2>Profile Inputs</h2>
        <div className="formHost">
          <JsonForms
            ajv={ajv}
            cells={vanillaCells}
            data={profile}
            onChange={({ data, errors: nextErrors }) => {
              setProfile((data ?? {}) as Record<string, unknown>);
              setErrors(nextErrors ?? []);
            }}
            renderers={vanillaRenderers}
            schema={generationProfileSchema as JsonSchema}
          />
        </div>
        <p className="status" data-valid={errors.length === 0}>
          Validation:{" "}
          {errors.length === 0 ? "valid" : `${errors.length} issue(s)`}
        </p>
      </section>

      <section className="panel">
        <h2>Generated generation profile JSON</h2>
        <pre>{generatedProfile}</pre>
      </section>
    </main>
  );
}

export default App;

// packages/gent-gui/src/App.vue
<script setup lang="ts">
import { createAjv, type JsonSchema } from "@jsonforms/core";
import { JsonForms, type JsonFormsChangeEvent } from "@jsonforms/vue";
import { vanillaRenderers } from "@jsonforms/vue-vanilla";
import type { ErrorObject } from "ajv";
import { computed, ref } from "vue";
import { generationProfileSchema } from "@gent-js/gent/generated/schema/generatedGenerationProfileSchema";
import { initialGenerationProfile } from "./schema/initialGenerationProfile";

const profile = ref<Record<string, unknown>>(
  structuredClone(initialGenerationProfile),
);
const errors = ref<ErrorObject[]>([]);

const ajv = createAjv({ allErrors: true, strict: false });

const generatedProfile = computed(() => JSON.stringify(profile.value, null, 2));

const isValid = computed(() => errors.value.length === 0);
const issueCountLabel = computed(() => `${errors.value.length} issue(s)`);

const handleChange = ({ data, errors: nextErrors }: JsonFormsChangeEvent) => {
  profile.value = (data ?? {}) as Record<string, unknown>;
  errors.value = (nextErrors ?? []) as ErrorObject[];
};
</script>

<template>
  <main class="app">
    <header>
      <h1>GenT Profile Builder</h1>
      <p class="lead">
        Fill in the form generated from the GenT generation profile schema.
      </p>
    </header>

    <section class="panel">
      <h2>Profile Inputs</h2>
      <div class="formHost">
        <JsonForms
          :ajv="ajv"
          :data="profile"
          :renderers="vanillaRenderers"
          :schema="generationProfileSchema as JsonSchema"
          @change="handleChange"
        />
      </div>
      <p class="status" :data-valid="isValid">
        Validation: {{ isValid ? "valid" : issueCountLabel }}
      </p>
    </section>

    <section class="panel">
      <h2>Generated generation profile JSON</h2>
      <pre>{{ generatedProfile }}</pre>
    </section>
  </main>
</template>

<style scoped>
.app {
  display: grid;
  gap: 1rem;
}

.lead {
  margin-top: 0.25rem;
  margin-bottom: 0;
  color: #4b5563;
}

.panel {
  border: 1px solid #d1d5db;
  border-radius: 8px;
  padding: 1rem;
  background: #ffffff;
}

.panel h2 {
  margin-top: 0;
  margin-bottom: 0.75rem;
  font-size: 1.1rem;
}

.formHost :deep(input),
.formHost :deep(select),
.formHost :deep(textarea) {
  width: 100%;
  box-sizing: border-box;
}

.status {
  margin-bottom: 0;
}

.status[data-valid="true"] {
  color: #166534;
}

.status[data-valid="false"] {
  color: #991b1b;
}

pre {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  background: #111827;
  color: #e5e7eb;
  border-radius: 8px;
  padding: 1rem;
  overflow: auto;
}
</style>
